version: '3.9'
services:
  db:
    image: mysql:8.0.36
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: swdish_spring_boot
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - 3308
    networks:
      - gustavo-networks
  swdish-spring-boot:
    image: gustavowmsilva/swdish-spring-boot
    restart: always
    build: ./demo3
    working_dir: /demo3
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/swdish_spring_boot?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: admin
      SPRING.DATASOURCE.PASSWORD: admin
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - gustavo-networks
networks:
  gustavo-networks:
    driver: bridge
